### ISSUE TITLE
[Docs] Fix README.md typos

### ISSUE THREAD

**Issue by mutairibassam** [mutairibassam/easy-twitter#10]
Project documentation should be well written and doesn’t have typos.

- Returns `a users'` followers details.

**Comment by t-bolt** [comment]
hello @mutairibassam.
i would like to work on this issue.

>Returns a users' followers details.
can you give some clarrifications on this please?

**Comment by mutairibassam** [comment]
Hi @t-bolt, It's just a typo needs to be modified. The statement should be written like this (**Returns a user's followers details**).

Please don't limit your contribution to this.
